steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ["--destination=gcr.io/PROJECTNAME/IMAGENAME",
         "--cache=true",
         "--cache-ttl=336h",
         "--verbosity=debug"]
timeout: 600s
